version: '3.8'
services:
  backend:
    image: backend
    ports:
      - 5000:5000
  frontend:
    image: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
